# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helloworld.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Teste")
        MainWindow.resize(449, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnClica = QtWidgets.QPushButton(self.centralwidget, clicked = lambda:  self.press_it())
        self.btnClica.setGeometry(QtCore.QRect(50, 350, 381, 181))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.btnClica.setFont(font)
        self.btnClica.setObjectName("btnClica")
        self.lblHello = QtWidgets.QLabel(self.centralwidget)
        self.lblHello.setGeometry(QtCore.QRect(100, 100, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lblHello.setFont(font)
        self.lblHello.setObjectName("lblHello")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def press_it(self):
        self.lblHello.setText('Boom!')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Teste"))
        self.btnClica.setText(_translate("MainWindow", "Clica"))
        self.lblHello.setText(_translate("MainWindow", "Hello Word!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
